### PR TITLE
Always show request parameter example description and summary

### PR DESCRIPTION
**Pull request by xeptore**
This PR make request parameter examples, which have description and summary. It first detects whether any of the request examples have any non-empty `description` or `summary` fields, then renders different contents based on that decision. For simple (_short format_) examples, it renders the examples in the previous layout. But, for examples which at least one of their items has a non-empty `description`, or `summary` (_long format_), renders an unordered list with each list item describes the example summary and markdown formatted optional description.

Changes I made:
- [x] Removed `use-summary-to-list-example` configuration option attribute
       As the example summary and description will be detected automagically, I couldn't find a use case for this option any more. Also, I tried to remove its occurrences from both documentation and source code. But, please have a closer look, if I missed any.
- [x] Added a long sample description with markdown styling for an example parameter in [`docs/specs/data-types.yaml`](https://github.com/rapi-doc/RapiDoc/compare/master...xeptore:master#diff-7c2d58575e023a5950026af0861e2e81f1923179daa3b3e8ba5af21df88c1ed8)
      In order to have an example to demonstrate the change
- [x] Updated the [`
src/components/api-request.js`](https://github.com/rapi-doc/RapiDoc/compare/master...xeptore:master#diff-8e0994f875e96985adc7136b31e1eb6fe2ba0b4ec504a11d5bfa5044d33fe600) component
       Mostly, separated rendering of short and long format examples, with a bit of code clean-up, code style polishing.
- [x] Added a helper function to [`
src/utils/schema-utils.js`](https://github.com/rapi-doc/RapiDoc/compare/master...xeptore:master#diff-82d61daee06cfa4e64b7d6351db4581c12a0b04c8d7f6f5960f970b8d0835c95)
       `anyExampleWithSummaryOrDescription` function to help identify type of examples, whether being long or short format type
- [x] Improved readability of `normalizeExamples` function in [`src/utils/schema-utils.js`](https://github.com/rapi-doc/RapiDoc/compare/master...xeptore:master#diff-82d61daee06cfa4e64b7d6351db4581c12a0b04c8d7f6f5960f970b8d0835c95)
- [x] Replaced uses of empty string with `∅` sign for empty example values ([here](https://github.com/xeptore/RapiDoc/blob/a6c0350e8bd33ff4fb6fd866201c3bd748786726/src/components/api-request.js#L254))

### CODE REVIEW

**Comment by xeptore** [comment]
Short format examples (simple array of string values):
Screenshot 2022-05-29 at 09-12-13 RapiDoc
Long format examples with summary and description:
Screenshot 2022-05-24 at 13-06-41 Radar API Documentation

**Comment by mrin9** [comment]
Thanks for the explanation and screenshot. Personally I like what you did with it. 
I will let it go through our UX team and then will review and merge

Thanks for the PR !!!

**Comment by xeptore** [comment]
OK. Great. I also updated the PR description, by adding another bullet point. Maybe it's worths having a look.

Cheers!

**Review by mrin9 — APPROVED** [review]

**Comment by xeptore** [comment]
@mrin9 I rebased this PR from `master`.

**Pull request merged**
