### PR TITLE
Add color pair for active nav items

### LINKED ISSUE #559: nav-hover-text-color is used for selected section
In modes with the sidebar, there is no dedicated `nav-selected-text-color` and `nav-hover-text-color` is used for that instead. That may result in unreadable text because of contrast, with no way to fix it.

Example color combination that is problematic:
```
theme="light"
nav-bg-color="#ffffff"
nav-text-color="#000000"
nav-hover-bg-color="#000000"
nav-hover-text-color="#ffffff"
primary-color="#000000"
```

### PR DESCRIPTION
**Pull request by afranke**
This is not completely working yet, but I have a hard time figuring out what’s missing.

Docs are also missing, but I wanted to get it working first.

Fixes #559

### CODE REVIEW

**Comment by mrin9** [comment]
thanks for attempting a fix on this, you said "This is not completely working yet"
so whats not working, do you want us to wait on this till it is fully working ?

**Comment by afranke** [comment]
As that was not a breaking issue for us, we went live with it! You can see it [here](https://matrix.org/docs/api/client-server/#overview). Maybe that helps with debugging?

**Comment by afranke** [comment]
The code for that page is [here](https://github.com/matrix-org/matrix.org/blob/master/rapidoc/index.html).

**Comment by mrin9** [comment]
When checking your live doc, when I hover on the tags the down chevron icon gets hidden I think due to same foreground and background color can we resolve that ?

**Comment by afranke** [comment]
> When checking your live doc, when I hover on the tags the down chevron icon gets hidden I think due to same foreground and background color can we resolve that ?

We probably can, but it should be in a different PR as it is unrelated to active nav items, right? It just happens to be exposed by the choice of colour combinations on our website, doesn’t it?

**Pull request closed without merging**
