### PR TITLE
Switch readonly/writeonly visibility in webhooks and callbacks

### PR DESCRIPTION
**Pull request by gherkz**
Addresses #727 

I have no idea if this is the best way of doing this, and wasn't sure if it warrants a new example or not. This change _does_ appear to work correctly, but I'm not going to pretend to fully understand the RapiDoc codebase so please do check it thoroughly first!

### CODE REVIEW

**Comment by mrin9** [comment]
Will look into it soon, 
this will break one of our following API behavior 

- `schema-hide-read-only` : here user can provide the method name such as `POST` , `PUT`,  `DELETE` or `GET` to specify where the `read-only` fields should be hidden

but we discussed internally that we would like to move away from this and be inline with the understanding that
- Hide ReadOnly for Requests 
- Hide WriteOnly for Responses
- Opposite is true in case of Web-Hooks and Callbacks 

CC @sneakyvv for any opinion on it as he introduced `schema-hide-read-only`  attribute to RapiDoc

**Comment by sneakyvv** [comment]
Hi @mrin9,

Let me quickly refer to the PR where this behavior was introduced: https://github.com/rapi-doc/RapiDoc/pull/383

I still feel that Rapidoc should allow to show the `readOnly` properties in `PUT` requests, to be completely in line with [the JSON Schema spec](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-9.4) :
> If "readOnly" has a value of boolean true, it indicates that the value of the instance is managed exclusively by the owning authority, and attempts by an application to modify the value of this property are expected to be ignored or rejected by that owning authority.

As the default behaviour of RapiDoc is to never show them for requests (i.e for the write methods, `POST`, `PUT` & `DELETE`), it's already in line with your interpretation of the spec. But again, a literal interpretation does not say that `readOnly` properties cannot be sent. 
The idea is that a resource retrieved via `GET` should be allowed to be sent with `PUT` without having to remove the `readOnly` properties. Technically the JSON schema (validation) will still allow them since in the actual schema they are present, only marked as `readOnly`. It's only the documentation which isn't showing them.
Furthermore, in combination with `"additionalProperties": false`, it might even be weirder. Although that isn't really shown in the rendered schema, it would imply that you can't send the `readOnly` properties, which simply isn't true. Only "attempts to modify the value [_should_] be ignored or rejected".

So, my proposal would be to not touch the current behaviour, but improve upon it for web-hooks and callbacks. I haven't really looked at the code changes in this PR, but at first glance it seems to do just that. If I find the time, I'll try to look at it soon.

**Comment by sneakyvv** [comment]
@gherkz 

> and wasn't sure if it warrants a new example or not

An extra example is always useful.
@mrin9 Is there perhaps already one using webhooks & callbacks?

**Comment by mrin9** [comment]
For now I am merging this as the solution is more closer to the spec
@sneakyvv we can revisit this if it needs to change it

**Comment by gherkz** [comment]
Sorry I wasn't very responsive on this issue - was away on vacation. Perhaps https://github.com/rapi-doc/RapiDoc/issues/727 can be closed now if you're happy the solution is complete

**Pull request merged**
